name: Quiz
description: "Create | Share | Discover"

publish_to: "none"

version: 1.8.19

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  get_it: ^7.6.7
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  animate_do: ^3.3.4


dev_dependencies:
  build_runner: ^2.4.8
  analyzer: ^6.4.1
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: "^0.13.1"


flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/
  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Bold.ttf
        - asset: assets/fonts/InterTight-Medium.ttf
        - asset: assets/fonts/InterTight-Regular.ttf
        - asset: assets/fonts/InterTight-SemiBold.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Bold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.otf
        - asset: assets/fonts/Inter-Regular.otf
flutter_intl:
  enabled: true
