name: Quiz
description: "Create | Share | Discover"

publish_to: "none"

version: 1.8.19

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  reusables:
    git:
      url: https://github.com/fatima-tehreem09/reusables.git
      ref: update
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_gen: ^5.4.0
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  gap: ^3.0.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  intl: any
  dartz: ^0.10.1
  get_it: ^7.6.7
  cloud_firestore: ^5.3.0
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^7.0.0
  retrofit: ^4.1.0
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  animate_do: ^3.3.4
  reorderable_grid_view: ^2.2.8
  lottie: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  analyzer: ^6.4.1
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  flutter_native_splash: ^2.4.0
  freezed: ^2.4.7
  flutter_launcher_icons: "^0.13.1"


flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/
#    - assets/images/app_logo.svg
#    - assets/veusax/outline/
#    - assets/svgs/
#    - assets/data/countries.json
#    - assets/
  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Bold.ttf
        - asset: assets/fonts/InterTight-Medium.ttf
        - asset: assets/fonts/InterTight-Regular.ttf
        - asset: assets/fonts/InterTight-SemiBold.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Bold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.otf
        - asset: assets/fonts/Inter-Regular.otf
flutter_intl:
  enabled: true
